# Generated by Django 4.1 on 2022-08-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminloginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='roll',
            field=models.IntegerField(max_length=255),
        ),
    ]
