# Generated by Django 4.1 on 2022-08-31 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminloginapp', '0002_alter_studentmodel_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='roll',
        ),
    ]
