# Generated by Django 4.1 on 2022-09-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminloginapp', '0003_remove_studentmodel_roll'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentModel',
            new_name='Student',
        ),
    ]
